version: "2.1"
services:
    emby:
        image: linuxserver/emby
        container_name: emby
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
            - UMASK_SET=022 #optional
        volumes:
            - ${TV_FOLDER}:/data/tvshows
            - ${MOVIES_FOLDER}:/data/movies
            - ./emby-backups:/backups
            - ./emby-config:/config
            - ./emby-transcode:/transcode #optional
        ports:
            - 8096:8096
            - 8920:8920 #optional
        devices:
            - /dev/dri:/dev/dri #optional
            - /dev/video10:/dev/video10 #optional
            - /dev/video11:/dev/video11 #optional
        restart: unless-stopped

    jackett:
        image: linuxserver/jackett
        container_name: jackett
        network_mode: host
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
    #      - RUN_OPTS=run options here #optional
        volumes:
            - ./jackett-config:/config
            - ${DOWNLOADS_FOLDER}:/downloads
        ports:
            - 9117:9117
        restart: unless-stopped
    radarr:
        image: linuxserver/radarr
        network_mode: host
        container_name: radarr
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
            - UMASK_SET=022 #optional
        volumes:
            - ./radarr-config:/config
            - ${MOVIES_FOLDER}:/movies
            - ${DOWNLOADS_FOLDER}:/downloads
        ports:
            - 7878:7878
        restart: unless-stopped
    sonarr:
        image: linuxserver/sonarr
        network_mode: host
        container_name: sonarr
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
            - UMASK_SET=022 #optional
        volumes:
          - ./sonarr-config:/config
          - ${TV_FOLDER}:/tv
          - ${DOWNLOADS_FOLDER}:/downloads
        ports:
          - 8989:8989
    
